name: "Postgres Exposure Check"
description: "Checks if provided Postgres hosts are publicly exposed by testing with invalid credentials"
author: "stjudd109"
branding:
  icon: 'alert-octagon'
  color: 'red'
inputs:
  postgres_hosts:
    description: "Comma-separated list of hostnames or IPs to check"
    required: false
  postgres_port:
    description: "Port to check (default: 5432)"
    required: false
    default: "5432"
  redshift_hosts:
    description: "Comma-separated list of hostnames or IPs to check"
    required: false
  redshift_port:
    description: "Port to check (default: 5439)"
    required: false
    default: "5439"
  hosts_json_file:
    description: "Path to a JSON file containing host information (format: {\"postgres_hosts\": [\"host1\", \"host2\"], \"redshift_hosts\": [\"host3\"]})"
    required: false
  timeout:
    description: "Connection timeout in seconds (default: 5)"
    required: false
    default: "5"
  sslmode:
    description: "SSL mode to use (default: prefer)"
    required: false
    default: "prefer"
  webhook_url:
    description: "Webhook URL for posting results (optional)"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    POSTGRES_HOSTS: ${{ inputs.postgres_hosts }}
    POSTGRES_PORT: ${{ inputs.postgres_port }}
    REDSHIFT_HOSTS: ${{ inputs.redshift_hosts }}
    REDSHIFT_PORT: ${{ inputs.redshift_port }}
    HOSTS_JSON_FILE: ${{ inputs.hosts_json_file }}
    SQL_TIMEOUT: ${{ inputs.timeout }}
    SQL_SSLMODE: ${{ inputs.sslmode }}
    RESULTS_WEBHOOK_URL: ${{ inputs.webhook_url }}
